steps:
- name: 'docker'
  args: ['build','-t','gcr.io/$PROJECT_ID/gcrapps','.']
images:
- 'gcr.io/$PROJECT_ID/gcrapps'

steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcrapps", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcrapps"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcrapps
  - --location=us-central1-a
  - --cluster=gke-gcrapps
  - --namespace=gcrapps