apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-deploy
  namespace: gcrapps
  labels:
    app: gcr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcr-app
  template:
    metadata:
      labels:
        app: gcr-app
    spec:
      containers:
      - name: gcp-container
        image: gcr.io/river-data-388020/gcrapps:latest
        ports:
        - containerPort: 5000
        env:
        - name: port 
          value: "5000"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gcp-svc"
  namespace: "gcrapps"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcr-app"
  type: "LoadBalancer"